# GitHub Issue Labels
# This file defines all labels used in the project
# Can be synced using github-label-sync or manually created

- name: "kalender"
  color: "24a200"
  description: "Neuer Adventskalender Vorschlag"

- name: "neu"
  color: "0E8A16"
  description: "Neue Einreichung"

- name: "bug"
  color: "d73a4a"
  description: "Etwas funktioniert nicht"

- name: "enhancement"
  color: "a2eeef"
  description: "Neue Funktion oder Verbesserung"

- name: "documentation"
  color: "0075ca"
  description: "Verbesserungen oder Ergänzungen zur Dokumentation"

- name: "duplicate"
  color: "cfd3d7"
  description: "Dieses Issue oder Pull Request existiert bereits"

- name: "wontfix"
  color: "ffffff"
  description: "Dies wird nicht bearbeitet"

- name: "invalid"
  color: "e4e669"
  description: "Dies scheint nicht richtig zu sein"

- name: "help wanted"
  color: "008672"
  description: "Zusätzliche Aufmerksamkeit wird benötigt"

- name: "good first issue"
  color: "7057ff"
  description: "Gut für Newcomer"
